### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by igordot** [hart-lab/bagel#11]
I tried BAGEL v2 build 113 with and without `--use-bootstrapping` using two different input tables. The fold-change tables are generated by BAGEL, so they should be properly formatted. I see the iterations loop, but then every time I get an error:

```
  File "/gpfs/home/software/BAGEL/2.0.113/BAGEL.py", line 700, in calculate_bayes_factors
    sumofbf += sum(bf[rnatag][i])
IndexError: list index out of range
```

I processed the same fold-change tables with BAGEL v0.92 and they worked.

Do you know what could be the problem?

**Comment by rooeikim** [comment]
Hi igordot,

Thank you for using BAGEL. 
We suspected the error is caused by duplicated sgRNA name. 
i.e. 

sgRNA_ID             GENE        Sample1 ...
**KRAS_AAA**            KRAS        0.232
**KRAS_AAA**            KRAS        0.153
KRAS_CCC            KRAS        0.524

or

sgRNA_ID             GENE        Sample1 ...
**AAAA**                    KRAS        0.232
GGGG                   KRAS        0.153
**AAAA**                    HRAS        0.524

Please change duplicated sgRNA tag to unique sgRNA tag, then it will work.
Also, we will add to show error messages for sgRNA tag duplicates.

Please let us know if you have any question.

**Comment by igordot** [comment]
You are right. I had some duplicated values in the first column. Fixing those resolved the issue.
