### ISSUE TITLE
errors when running precalc_library_alignment_info.py

### ISSUE THREAD

**Issue by acousticus** [hart-lab/bagel#22]
Thank you for this excellent software.

I am interested in running BAGEL2 with Multi-target-filtering. 
I therefore tried to use precalc_library_alignment_info.py to generate an alignment-info for TKOv1
Unfortunately the script would not complete, and generated errors that I traced back to: 

`for readid in guideid2seq_series:`

In an effort to debug, I replaced the above with
`for readid in guideid2seq_series.index:`

I also used an input file with lowercase headers corresponding to this call (rather than uppercase as in the helptext) ie:

[READID2SEQ] format:
readid [tab] guideseq
READ1  [tab] ATAGATGTCCTGTGGCCCCG`

With those two changes it seemed to run smoothly and generate an alignment file. 
However, I am not sure if this is a genuine bug with the current version that others experience, or simply a mistake on my part with the input files / system setup (python 3.7.3)?

Many thanks

**Comment by acousticus** [comment]
Thanks for this. Please could you let me know which old version of pandas the current release should still run on?

**Comment by rooeikim** [comment]
I generated this code under python 2.7 enviroment and converted into python 3 version after. 
And, I'm guessing something went wrong during the conversion. 
Since I tested it using a READID2SEQ file that I duplicated the sequence column as a read ID, the bug couldn't detected.
I've uploaded updated version, so please use the code.
Thank you again for reporting this issue.

**Comment by acousticus** [comment]
You're very welcome. Thank you for fixing this; I can confirm it ran successfully in a python 3.7.3 environment.
